### ISSUE TITLE
Add hands class to target all hands

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#10]
Right now the hand classes do not have a single SVG class to target them all, just individual ones. It's necessary to have a single class that targets all hand positions together so they can be animated up/down alongside the body.

**Comment by mudgen** [comment]
Right now there is the class `gotchi-handsDownOpen` which targets both hands down and open.

And there is the class `gotchi-handsUp` that targets both hands up.

The `gotchi-handsDownClosed` class targets both hands down and closed.

**Comment by cinnabarhorse** [comment]
Great, thanks.
