### ISSUE TITLE
Colors are inverted on handsUp position

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#11]
You can see the darker color should be on the outside, and lighter on the inside, but it appears to be reversed

![image](https://user-images.githubusercontent.com/6047087/102782100-bd6b0500-43d3-11eb-9b1f-9913dc03430d.png)

**Comment by mudgen** [comment]
Thanks for this.   Fixed this: 84bd1cb30d745304f8ed2608a273610d8a19ca60

**Comment by cinnabarhorse** [comment]
Nice, closed.
