### ISSUE TITLE
Add functions that return which wearables a certain account (or aavegotchi) holds, of a specific wearable slot

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#12]
Maybe possible to make this broader so it can apply to all types of items, not just wearables?

**Comment by mudgen** [comment]
Yes.

I added the following functions to ItemsFacet:
```Solidity
struct ItemBalanceWithSlotsIO {
        uint256 itemId;
        uint256 balance;
        uint256[] slotPositions;
    }

function itemBalancesOfTokenWithSlots(address _tokenContract, uint256 _tokenId)
    external
    view
    returns (ItemBalanceWithSlotsIO[] memory itemBalanceWithSlots_)

function itemBalancesWithSlots(address _owner) 
    external 
    view 
    returns (ItemBalanceWithSlotsIO[] memory itemBalanceWithSlots_)
```

Commit: 325ec68100e9d052226219b58319fb852e736fe8

**Comment by cinnabarhorse** [comment]
Yes, I think it'd be good to add those as well so I can use them on the frontend. especially `traitModifiers`, `minLevel`, and the name of the wearable.

**Comment by cinnabarhorse** [comment]
Added the traitModifiers and name

**Comment by mudgen** [comment]
I changed traitModifiers to an array instead of uint256 and I added minLevel.

**Comment by cinnabarhorse** [comment]
Great, closed.
