### ISSUE TITLE
Update IAavegotchiDiamond.sol so diamond ABI can be used

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/aavegotchi-contracts#14]

**Comment by mudgen** [comment]
I updated `contracts/Aavegotchi/interaces/IAavegotchiDiamond.sol` with all the external functions and events from the facets.

The diamond ABI can be gotten here: https://github.com/aavegotchi/aavegotchi-contracts/blob/master/artifacts/contracts/Aavegotchi/interfaces/IAavegotchiDiamond.sol/IAavegotchiDiamond.json


Commit hash: b33a181276f04a21adcba023bfcf71cb79b87e86

**Comment by cinnabarhorse** [comment]
Nice, having some issues integrating this ABI into the subgraph. Will post an update after I try again.

**Comment by cinnabarhorse** [comment]
The subgraph scaffolder runs after commenting out all of the multidimensional array functions in the ABI. Closed for now.
