### ISSUE TITLE
Onchain Runner sets have Wine instead of Water Jug

### ISSUE THREAD

**Issue by mistaya** [aavegotchi/aavegotchi-contracts#143]
This was fixed on the wiki and on app.aavegotchi.com (https://github.com/aavegotchi/aavegotchi-contracts/commit/f81369f031d5c69c5779764d8bd1b432b6e229fa#diff-960e4a0be23f3be297efc0ff8a0adda4786e72d7ab9d83d2a1fd986d7e674435L287), but the onchain sets haven't been updated.

`ItemsFacet.getWearableSets` still has Wine (121) instead of Water Jug (118) in the "Runner" and "Long Distance Runner" sets.

**Comment by cinnabarhorse** [comment]
Updated and pushed onchain in https://github.com/aavegotchi/aavegotchi-contracts/commit/6aef490cead8bd4cd934cf7f3ab73fb00b42e5b4. Thanks!
