### ISSUE TITLE
Numeric traits in portalAavegotchis should include the collateral modifier

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#18]
Right now the collateral modifier isn't included in the `numericTraits` of `singlePortalAavegotchiTraits` return. This should be fixed so the buyer knows exactly what the numeric traits of their Aavegotchi will be.

**Comment by mudgen** [comment]
Yes, good catch. Fixed: 4a177e2a3a7e86d5d2d95b3b7df077c128a2b5c8

I noticed that the return value of `getAavegotchi` does not include trait modifications by any equipped wearables.   I'm thinking that the `getNumericTraits` function should include equipped wearable trait modifications.

**Comment by cinnabarhorse** [comment]
Yes it definitely should. I was thinking we can return a "numericTraits" and a "modifiedNumericTraits" that includes the wearables.

**Comment by cinnabarhorse** [comment]
Mentioned this in https://github.com/aavegotchi/aavegotchi-contracts/issues/15 btw

**Comment by mudgen** [comment]
Commit: e8d9fd45b3b5d5c8870b7a53df1d52690c78c72f

I changed the `modifiedRarityScore` function to `modifiedTriatsAndRarityScore`.  It returns the modified traits and rarity score. This is called in the `getAavegotchi` function.

The getAavegotchi function returns `numericTraits` and `modifiedNumericTraits`

`modifiedNumericTraits` includes traits that are modified by consumables and wearables.
The `rarityScore` includes modifications by consumables and wearables.

**Comment by cinnabarhorse** [comment]
Great, closed.
