### ISSUE TITLE
[UPGRADE] useConsumable should take multiple IDs and quantities

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#19]
Initially I believe we decided to restrict useConsumable to only one item, but to help users save gas it makes more sense to allow multiple items. So let's change it back to taking an array of IDs and quantities.

Let's make this change as an upgrade to the currently deployed AavegotchiDiamond contract: `0xDdC64462aEBA340cBE52E2B64eef20D0B23B5126`.

**Comment by mudgen** [comment]
Done. Commit: bd9436f9e1b77248bd6c0b243a7f615189497295

Yes, this can be change in an upgrade.

**Comment by cinnabarhorse** [comment]
Great, closed.
