### ISSUE TITLE
[UPGRADE] Allow interact() to be batched

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#20]
Currently we can only call `interact()` for one gotchi at a time. This prevents us from creating "gotchi walker" roles. It would be great if `interact()` took an array of tokenIds instead of just one. 

This can be done as an upgrade on the current deployed Aavegotchi Diamond `0xDdC64462aEBA340cBE52E2B64eef20D0B23B5126` , if possible.

**Comment by mudgen** [comment]
Yes, this is done. Commit: 257b36c51477965223b8853ae56882c5fb6b1b7d

Yes, this can be done as an upgrade.

**Comment by cinnabarhorse** [comment]
Great, closed.
