### ISSUE TITLE
Aavegotchi collateral sign is showing on aWETH Aavegotchi

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#21]
![image](https://user-images.githubusercontent.com/6047087/103154021-dc9cd480-47cf-11eb-9c39-4d8fc4ac172c.png)

**Comment by mudgen** [comment]
Thanks.  I fixed this by putting in sync the data between `colalteralTypes.js` and `eyeShapes.svg`.

However this work is not fully done yet because I don't yet have an SVG file for the tether USDT collateral.

**Comment by mudgen** [comment]
I got the updated SVG file for USDT and updated the data.  Commit: 4fc03fd8e3c1db30061d97c955c7bec93bba4f95

**Comment by cinnabarhorse** [comment]
Great, closed.
