### ISSUE TITLE
New DAO function: updateItemType

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#23]
Some items like XP potions have a fixed quantity to begin with, but could be periodically "refilled" by increasing the `maxAmount`. This could be a good DAO function.

**Comment by mudgen** [comment]
Yes, should the function be called something like `updateItemTypeMaxQuantity(uint256 _newQuanity)`  or is a generic function wanted to change any item type value?

Diamond upgrades have the ability to execute custom code that can update/modify any state variable of the diamond.  This can be used to update/change itemType variables and other things.

**Comment by cinnabarhorse** [comment]
Having a standalone function for that single purpose could be pretty nice. This will be a pretty common function to call (by us and the DAO) so I'd rather it not be an upgrade. 

For now I think it's fine to only support updating max quantity. It can take the `[itemIds]` and the `[maxQuantities]` params.

**Comment by mudgen** [comment]
Yes, I added the `updateItemTypeMaxQuantity(uint256[] calldata _itemIds, uint32[] calldata _maxQuantities)` function.

**Comment by cinnabarhorse** [comment]
Great, closed.
