### ISSUE TITLE
Return "locked" status in getAavegotchi

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#24]
Currently we are not returning whether or not an Aavegotchi is `locked` in `getAavegotchi()`. This is necessary information for the frontend UI so we can restrict certain functions while the Aavegotchi is locked.

To do: Return `locked` as a bool, and if `locked=true` then return the `unlockTime`. If not locked, can just return `0` for `unlockTime`.

**Comment by mudgen** [comment]
Yes, this is good.  I added these. Commit: f279d5d832dbc4ef18f135e6f310d6e6450f6ebd

**Comment by cinnabarhorse** [comment]
Great, closed.
