### ISSUE TITLE
Handle handLeft and handRight in itemTypes.js

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#25]
Most hand wearables look fine in both hands, but some (like the REKT sign) only looks good in the left hand. So we should handle left and right hands separately when adding the items.

**Comment by mudgen** [comment]
I added handLeft and handRight to the `itemTypes.js` file.   I set the REKT sign wearable to `handLeft`.   Are there other wearables we should set to `handLeft` or `handRight` ?

**Comment by cinnabarhorse** [comment]
Yes so far I believe REKT sign is the only one. The DAO Egg will probably also be a single hand wearable. Closed for now.
