### ISSUE TITLE
Update SVG functions and files for items to use x, y, width, height

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/aavegotchi-contracts#27]

**Comment by mudgen** [comment]
I updated the facets with the logic to use x, y, width, height for displaying items and wearables.  Need to update the item x, y, width, height data.

**Comment by mudgen** [comment]
Data has been updated.   The mirroring of hand wearables was also modified to work with this.

**Comment by cinnabarhorse** [comment]
Great, closed.
