### ISSUE TITLE
Allow batch transfer of items from parent in ItemsFacet

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#28]
Currently the erc1155 method `transferFromParent()` only implements a single token ID to transfer. Would be nice if it could be extended to implement a `batchTransferFromParent()` function similar to below. Not urgent though.
```
  function batchTransferFromParent(
        address _fromContract,
        uint256 _fromTokenId,
        address _to,
        uint256[] _ids,
        uint256[] _values
    ) external
```

**Comment by mudgen** [comment]
This is implemented. Commit: f2cd56353c2bf71dba87cd9e9fc8a7eba501f64c

Should transferring items/wearables in and out of an Aavegotchi call the `interact` function to help the Aavegotchi's kinship?

**Comment by cinnabarhorse** [comment]
Probably not, just equipping or un-equipping them I think.
