### ISSUE TITLE
Return traitModifiers as an array instead of a uint in all the item functions

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#29]
`getItems()` and all the other item functions are still returning `traitModifiers` as uints instead of int8 arrays. Would be better for developers if they were arrays.

**Comment by mudgen** [comment]
Yes, I updated the `getItemType` and `getItemTypes` functions so they return arrays rather than uint256.

Commit: 572425ad9fbc9651f8dded1b10585f266db782a0

**Comment by cinnabarhorse** [comment]
Nice, closed.
