### ISSUE TITLE
Improve return of numericTraits in portalAavegotchiTraits()

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#3]
Currently the value of `numericTraits` is unconverted int256, not an easily-readable array. Perhaps vit would be easier for developers if `numericTraits` were returned as a uint8 array, not an int256 number (but it can still be stored in memory as the int256)

**Comment by mudgen** [comment]
In some cases the numericTraits uint256 is needed.  So I made numericTraits an array of int16 and added another variable 'numericTraitsUint` which is the uint256 version.

Commit here: ea42c8ad93919d2fc4b737bbdbbc0fe7ee60f759

**Comment by cinnabarhorse** [comment]
Great, thanks. Closed.
