### ISSUE TITLE
Unlock aavegotchi after transferring

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#30]
An Aavegotchi should be unlocked after a successful transfer. Otherwise we will have a lot of locked Aavegotchis and a potentially bad UX.

**Comment by mudgen** [comment]
This is done.  Commit: fdbf92ad216749bbc2554afa953cf2043f2304d9

**Comment by cinnabarhorse** [comment]
Great, closed.
