### ISSUE TITLE
Implement ERC721Metadata for Aavegotchi

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/aavegotchi-contracts#31]
I think we need to implement the following interface from the ERC721 standard so that services like OpenSea can interact with the Aavegotchi's metadata:

```Solidity
/// @title ERC-721 Non-Fungible Token Standard, optional metadata extension
/// @dev See https://eips.ethereum.org/EIPS/eip-721
///  Note: the ERC-165 identifier for this interface is 0x5b5e139f.
interface ERC721Metadata /* is ERC721 */ {
    /// @notice A descriptive name for a collection of NFTs in this contract
    function name() external view returns (string _name);

    /// @notice An abbreviated name for NFTs in this contract
    function symbol() external view returns (string _symbol);

    /// @notice A distinct Uniform Resource Identifier (URI) for a given asset.
    /// @dev Throws if `_tokenId` is not a valid NFT. URIs are defined in RFC
    ///  3986. The URI may point to a JSON file that conforms to the "ERC721
    ///  Metadata JSON Schema".
    function tokenURI(uint256 _tokenId) external view returns (string);
}
```
@cinnabarhorse What should be the `baseUri` value used by tokenURI?  Could be `https://aavegotchi.com/metadata/aavegotchis/`

The value of name could be `Aavegotchi`.   What should the abbreviated name symbol be?   "Gotchi"  or "AGotchi"  or "AGI"

**Comment by cinnabarhorse** [comment]
Yes I can implement these today. The name can be Aavegotchi. The symbol can be AAVG? Yes the url can be what you listed above there. I'll need to setup a cloud function that uses our infura key to hit the `getAavegotchi` and `getAavegotchiSvg()` methods, and maybe some others. Fun.

**Comment by mudgen** [comment]
Good work!

**Comment by cinnabarhorse** [comment]
Implemented in https://github.com/aavegotchi/aavegotchi-contracts/commit/b91032617145c8a43dc417a61708184beddd51ae.
