### ISSUE TITLE
Create a new modifier onlyOwnerOrDaoOrGameManager

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#33]
We'll use this for day-to-day operational functions. After creating the modifier, please add it to: 

`grantExperience()` and
`updateItemMaxQuantity()`

**Comment by mudgen** [comment]
Yes.  Done. commit: 64f17562db86df8aee2acbd48f42f78362c4f98a

**Comment by cinnabarhorse** [comment]
Great, closed.
