### ISSUE TITLE
Enable metatransactions throughout the contract

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#36]
Matic supports meta transactions (gasless transactions) and suggests we use Biconomy as a service provider. We will need to make some small changes to our smart contracts to enable these. 

https://docs.biconomy.io/tutorials/native-meta-transactions

https://github.com/bcnmy/metatx-standard

**Comment by cinnabarhorse** [comment]
We can start by making a small demo contract and deploying to Mumbai with a demo UI so users can start experiencing metatransactions on Matic.

**Comment by cinnabarhorse** [comment]
@mudgen anything left to add for this? If not I will close.

**Comment by mudgen** [comment]
I have modified the metatransactions in the contract to work so that Ethereum can be connected in metamask but the metatransactions can be for Matic Network.   But if we aren't going to do this,  and I don't think we should,  then I think I should change metatransactions back to the way they were before because I think that's more standard.

**Comment by cinnabarhorse** [comment]
Yes I agree, let's change them back to the original configuration.

**Comment by mudgen** [comment]
I think the only change to make it back to how it was originally is changing the constant to this:
```
bytes32 internal constant EIP712_DOMAIN_TYPEHASH =
        keccak256(bytes("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"));
```
I think you will have to make a related change in the UI.

It is done in the contract.

Commit: a540cc09f794225915f6ec5dba24fbaea1d821d9

**Comment by mudgen** [comment]
This is done in AavegotchiDiamond -- need to do it for GHSTStakingDiamond

**Comment by cinnabarhorse** [comment]
Completed.
