### ISSUE TITLE
Equipping the same wearable twice

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/aavegotchi-contracts#37]
Owner only owns one wearable but can equip it twice. Fix this.

**Comment by cinnabarhorse** [comment]
Has this been fixed yet? @mudgen

**Comment by mudgen** [comment]
It looks like to me this could only be done with hand wearables.  I fixed this so that a user must have at least 2 of the same hand wearable to equip it in both hands, otherwise it reverts.

**Comment by mudgen** [comment]
Oh,  I fixed this.   I'm sorry,  I don't have the commit hash.

**Comment by cinnabarhorse** [comment]
Probably this one: https://github.com/aavegotchi/aavegotchi-contracts/commit/e97e39115d54b227f6cf79421fb5664dc7daa026
