### ISSUE TITLE
Limit number of portals buyable in one transaction

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#4]
We should limit the number of portals that a user can portal in one transaction, to prevent a large user from buying them all in one go. 50 would be a good number.

**Comment by mudgen** [comment]
I set the maximum number of portals that can be purchased in one call to `openPortals` to 50.

However it is still possible to purchase more than 50 portals in a single transaction by calling `openPortals` multiple times within the same transaction. 

But setting the maximum number of portals that can be purchased in one call to `openPortals` makes it harder to purchase more than that in a single transaction and increases the gas cost to do so and reduces the total number that can be purchased in a single transaction.  The block gas limit determines the maximum number of portals that can be purchased in single transaction.

Commit:  6eea94e27f2ca7ec35d69e42508306bbae2e8fb0

**Comment by cinnabarhorse** [comment]
Yes, I see what you mean. Someone very motivated to get all of the Portals in one block could spam multiple `buyPortals` transactions in the same block. But I think it's good to have the hard-coded limit nonetheless. 

Closed for now.
