### ISSUE TITLE
Change rarity score formula to use 0-99 

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#41]
Currently rarity score is calculated from 0-100. It should actually only be from 0-99. 

To fix this, we need to update the traits to only range from 0-99, and then update how BRS is calculated, using the following formula:

```
x < 50 : 100 - x
x >= 50: x+1
```

**Comment by mudgen** [comment]
This is done.   Was done in the past sometime.  Don't know where the commit is.

**Comment by cinnabarhorse** [comment]
Okay, great.
