### ISSUE TITLE
Bridging NFTs

### ISSUE THREAD

**Issue by mudgen** [aavegotchi/aavegotchi-contracts#42]
### Withdrawing Aavegotchis & Portals from Matic

Here is information needed for user interfaces for bridging Aavegotchis and portals:

This is the function to call on the AavegotchiDiamond to lock and withdraw Aavegotchis and portals on Matic Network:
` function withdrawAavegotchiBatch(uint256[] calldata _tokenIds) external`. Call that contract function on Matic Network.

Get the transaction hash for that transaction.

Call the `exitBatchERC721(txHash: string, options?: SendOptions)`  from maticjs,  from their ` MaticPOSClient` class.  Note that this function is not in their documentation but it is in their source code. This function gets called on Ethereum on Matic's standard RootChainManger contract.

### Withdrawing Aavegotchi Items from Matic

This is the function to call on the AavegotchiDiamond to withdraw Aavegotchis items on Matic Network:
`function withdrawItemsBatch(uint256[] calldata _ids, uint256[] calldata _values) external`. Call that contract function on Matic Network.

Call the `exitBatchERC1155(txHash: string, options?: SendOptions)`  from maticjs,  from their ` MaticPOSClient` class.  Note that this function is not in their documentation but it is in their source code. This function gets called on Ethereum on Matic's standard RootChainManger contract.

**Comment by mudgen** [comment]
Fixed the bridge issue.  Commit: 85fd3e6ff6fc4082da194e78ce4dce038c9ec476

**Comment by cinnabarhorse** [comment]
Great, closing.
