### ISSUE TITLE
Listing not updated after being executed

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#43]
The quantity in the ERC1155 listing is not being updated after it has been executed. The seller's balance is lowered and the buyer's balanced is increased, but the listing is not updated.

**Comment by mudgen** [comment]
Thank you for finding this.  You are correct.   I fixed it.

**Comment by cinnabarhorse** [comment]
Great, once you've pushed you can drop the commit tag here and I'll close.

**Comment by mudgen** [comment]
Okay,  commit here: 77bfefff8fedd4f2b56f476c2f671d73344dae9c

**Comment by cinnabarhorse** [comment]
Great, closed.
