### ISSUE TITLE
getERC1155Listings returns more listings than are open

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#44]
After creating a few listings, calling getERC1155Listings with params "0", "listed", 20 results in 20 listings, even though there should only be 2 unique listings.

**Comment by mudgen** [comment]
I think this was already fixed at an earlier time but after the diamond was deployed, as the code looks correct.

**Comment by mudgen** [comment]
Let's try this again to see if it works now.   New diamond was deployed yesterday.

**Comment by cinnabarhorse** [comment]
Yep, it's fixed.

**Comment by cinnabarhorse** [comment]
Re-opening because I just saw this happen again with the latest deployment.

**Comment by cinnabarhorse** [comment]
@mudgen This should be fixed now, right?

**Comment by mudgen** [comment]
Yes

**Comment by cinnabarhorse** [comment]
Great, closing.
