### ISSUE TITLE
Change Mumbai VRF to 0.001 LINK / call

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#45]
Right now the portal opening is set to use 1 LINK per call. It would be better if it were set to 0.001 so we would not need to constantly use the faucet.

**Comment by mudgen** [comment]
This is done.   Chainlink says the fee is `0.0001` so I changed it to that for all networks.  I also updated the matic network info with the configuration that chainlink recently gave us.

Commit: 216ee14300537bc4aaa4c8ab73c2b8c6652b8aa7

**Comment by cinnabarhorse** [comment]
Great, closing.
