### ISSUE TITLE
Should we add ghstPrice to raffle wearables?

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#48]
All of the shop wearables have a `ghstPrice` field that shows their price in the store. Since raffle wearables were not sold in the store, their price is 0. However, it may be beneficial to assign an estimated GHST price to the raffle wearables, so we can help estimate how much an Aavegotchi is worthy (based on how many wearable it is holding)

**Comment by mudgen** [comment]
I think part of the challenge and fun of the game is determining or finding out how much things should cost.  I say let the market decide.   But you are the boss, boss, and I'm happy either way.

**Comment by cinnabarhorse** [comment]
This has been implemented in https://github.com/aavegotchi/aavegotchi-contracts/commit/3b19f6e638206dd7752c25666d5599674ffe5d6b.
