### ISSUE TITLE
Remove cancelled and sold portals from getERC721Listing

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#49]
Don't show cancelled and sold portals in the getERC721Listings function

**Comment by mudgen** [comment]
okay.  It's supposed to do that already,  remove from the "listed"   list.  So I'm writing a test to help debug what is going on.

**Comment by mudgen** [comment]
I wrote the test, debugged the issue. You were right that his was happening. I found the problem and fixed it.   It now works as expected.

Commit: 5fb56d8c8fae5a4ab0d67d8211dd753b71ebcc54

Question: When a listing is cancelled or sold should it also be removed from the user's list of listings?   

It could be removed from the users "listed" list  and be added to his "purchased" or "cancelled" list.  What should it be?

**Comment by cinnabarhorse** [comment]
Cancelled should be removed, yes. It can be added to the user who purchased it's "purchased" list. 

Closing this for now.
