### ISSUE TITLE
Remove cancelled and sold listings from getUserERC1155Listings

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#50]
![image](https://user-images.githubusercontent.com/6047087/107880668-58d3ae80-6f1b-11eb-80db-d6808046a4f9.png)

**Comment by mudgen** [comment]
Yes, this was done.

Commit: e50446fd0d8d07b74bbcc73a2c460bcdecfa363d


```
 function getERC1155Listings(
        uint256 _category, // // 0 is wearable, 1 is badge, 2 is consumable, 3 is tickets
        string memory _sort, // "listed" or "purchased"
        uint256 _length // how many items to get back or the rest available
    ) external view returns (ERC1155Listing[] memory listings_) {
```

Use the "purchased" sort to get purchased listings,   get "listed"  to get currently listed ones.

Note:  All listingIds have been changed from bytes32 to uint256

**Comment by cinnabarhorse** [comment]
Great, closed.
