### ISSUE TITLE
Add maToken collaterals to contract deployment

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#55]
We need to add the correct collateral addresses for maTokens in the `collateralTypes.js` file.

**Comment by cinnabarhorse** [comment]
Started this by adding in the collateral.maticAddress object in `collateralTypes.js`. Also updated the GHST address to the correct address on Matic.

**Comment by mudgen** [comment]
Thanks.  I added all the maToken addresses.   I also updated the conversion rates.  Should we change the names of the collaterals so they start with `ma` instead of `a` ?

**Comment by cinnabarhorse** [comment]
Nah aToken is fine. Closing!
