### ISSUE TITLE
Use arrays instead of uint256s for traitModifiers, numericTraits, modifiedNumericTraits, slotPositions

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#57]
Since we're on Matic we don't need to worry as much about gas optimization, so let's change these uint256s back into arrays for code legibility.

**Comment by mudgen** [comment]
This was done.  Commit here: 50b32ad61d96ed1758b7dd3d106149b0cd476384

**Comment by cinnabarhorse** [comment]
Great!
