### ISSUE TITLE
Locked=false after updating a listing

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#58]
As demonstrated earlier, in the ERC721MarketplaceFacet if one adds a listing to an existing listing, it cancels the previous listing but due to order of operations the `locked` variable remains at false, even though the Aavegotchi is listed. This is a security bug that should be addressed.

**Comment by mudgen** [comment]
Yes, this is a very good catch.   I looked this over more and the solution and fix we have now is good.   The Aavegotchi is re-locked  at the end of the `addERC721Listing` function.  

Fixed.  Commit: 4f527cc78551176ec7dd69b5afd8e870d66b70f6

**Comment by cinnabarhorse** [comment]
Great, closing.
