### ISSUE TITLE
getERC1155Listings returning listigs that have quantity=0

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#59]
The function shouldn't be returning empty listings.

**Comment by mudgen** [comment]
What category of items did this happen with?

**Comment by cinnabarhorse** [comment]
At least wearables, I didn't test it with consumables. I noticed it in the wild, there wasn't a specific process to get this result.

**Comment by cinnabarhorse** [comment]
This is happening after I list a wearable then transfer it to my aavegotchi. The quantity is 0 but cancelled is not set to true.

**Comment by cinnabarhorse** [comment]
Closing since this is complete.
