### ISSUE TITLE
Allow user to interact meaningfully with Aavegotchi immediately after claiming

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#6]
Currently the user needs to wait 12 hours after the Aavegotchi has been claimed from the Portal for the `interact()` to increase Kinship. It would be nice if the player could interact once with the Aavegotchi to increase Kinship immediately after it is claimed from the Portal.

**Comment by mudgen** [comment]
This is done: 4f06e2e38710c3814b576515497c957c09cedb2c

When an Aavegotchi is claimed `lastInteracted` is set to `block.timestamp - 12 hours`

This means it can be interacted with right away.  It also means that the first kinship point can be lost after 12 hours.   

A kinship point is lost every 24 hours if it isn't interacted with.  But when an Aavegotchi is first claimed the first 12 hours are lost so it can be interacted with right away.  An interaction can happen every 12 hours.

**Comment by cinnabarhorse** [comment]
Great, closed.
