### ISSUE TITLE
Add array of all items held by Aavegotchi in getAavegotchi, getAavegotchiListing, and getAavegotchiListings

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#60]
So we don't have to perform a second query to check what items an Aavegotchi is holding (to help determine its value)

**Comment by mudgen** [comment]
This is done:  Commit: 841af147b410da723a2c21a2eeb16abe99d25ee6

**Comment by cinnabarhorse** [comment]
Great, closing.
