### ISSUE TITLE
Possible name bug

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#63]
One user has reported that naming an Aavegotchi, renaming it, then trying to name another gotchi with the original name fails. Possible bug related to storing names.

**Comment by mudgen** [comment]
Yes, this was helpful.  The bug was found and fixed. Commit: 689ed07897d981d6dd2c31f8d811d5946210e7af

**Comment by cinnabarhorse** [comment]
Great, closing.
