### ISSUE TITLE
Use Aave SVG and collateral info instead of LEND 

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#7]
We are still using the old LEND Svgs but those will not be supported in launch. We should switch to the Aave Svg and collateral ASAP.

**Comment by cinnabarhorse** [comment]
AAVE collateral info:

            primary: "#B6509E",
            secondary: "#CFEEF4"

**Comment by mudgen** [comment]
Updated and replaced LEND SVG with AAVE SVG: d7e9870a101072588c73025f8638a91ad6bcada3

**Comment by cinnabarhorse** [comment]
Great, closed.
