### ISSUE TITLE
getAavegotchiListings( _category, 'purchased', _length) works only with small datasets

### ISSUE THREAD

**Issue by Juglipaff** [aavegotchi/aavegotchi-contracts#77]
Not sure if this is intentional or not, but right now **getAavegotchiListings(3, 'purchased', 800)** throws '_cannot estimate gas_' error, while **getERC721Listings(3, 'purchased', 800)** returns an array with 800 elements. 

**getAavegotchiListings** works, but only up to around ~100 elements

**Comment by cinnabarhorse** [comment]
Hm not really intentional, but more a limitation given the amount of data that `getAavegotchiListings` returns. Our smart contract is close to being deployed and once it's ready it'll be much easier to query the listings (won't need to use the SC directly).
