### ISSUE TITLE
Portal Aavegotchis don't have hands

### ISSUE THREAD

**Issue by cinnabarhorse** [aavegotchi/aavegotchi-contracts#8]
![image](https://user-images.githubusercontent.com/6047087/102714819-4a4a8b80-430c-11eb-9073-8275a6e8ccd4.png)

**Comment by mudgen** [comment]
I fixed this: 2092139175e24d0fab8548da718711c9c0f8bb50

Some notes:

Here are the possible hand positions:
1. Hands down and closed.  This is the default position.
2. Hands down and open. This is the position when the Aavegotchi is wearing a body wearable or a hand wearable.
3. Hands up -- this is set by a user interface.

All three hand position SVGs are included in the overall SVG.   
To be consistent the SVGs are using only classes and not ids in CSS.

All classes are prefixed with `gotchi-` to ensure there are no CSS conflicts.

To make things appear or disappear the CSS `display` property is used.  For example: `display: none;` or `display:block`.

Here are the CSS classes for hands and sleeves:
- gotchi-sleevesUp
- gotchi-sleevesDown
- gotchi-handsUp
- gotchi-handsDownOpen
- gotchi-handsDownClosed

**Comment by cinnabarhorse** [comment]
Great, closed.
