### ISSUE TITLE
what is the address of process.env.DIAMOND_UPGRADER

### ISSUE THREAD

**Issue by JoyCood** [aavegotchi/aavegotchi-contracts#81]
could you tell me the address of **process.env.DIAMOND_UPGRADER** in the 

> scripts/libraries/multisig/example.js file
@mudgen thanks

**Comment by cinnabarhorse** [comment]
The address is 0x35FE3dF776474a7B24B3B1EC6e745a830FdAd351

**Comment by JoyCood** [comment]
> The address is 0x35FE3dF776474a7B24B3B1EC6e745a830FdAd351

it's not a contract? when i search by the address from etherscan.io, can not find any contract content there.

**Comment by mudgen** [comment]
> > The address is 0x35FE3dF776474a7B24B3B1EC6e745a830FdAd351
> 
> it's not a contract? when i search by the address from etherscan.io, can not find any contract content there.

That's because the contract is on Polygon, not Ethereum.

**Comment by Timidan** [comment]
https://explorer-mainnet.maticvigil.com/address/0x35FE3dF776474a7B24B3B1EC6e745a830FdAd351/transactions

**Comment by JoyCood** [comment]
> > > The address is 0x35FE3dF776474a7B24B3B1EC6e745a830FdAd351
> > 
> > 
> > it's not a contract? when i search by the address from etherscan.io, can not find any contract content there.
> 
> That's because the contract is on Polygon, not Ethereum.

and this project have no deploy script for this contract?
